version: '3.8'

services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/alimaskin/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped

volumes:
  open-webui:
